#!/usr/bin/python3

import sys
import requests
import argparse
import traceback

from chanapi import *

domain = 'kohlchan.net'
base_url = 'https://' + domain
parser = argparse.ArgumentParser(description='post to '+domain)
parser.add_argument('url',                help='URL or board')
parser.add_argument('text',               help='Specift - for STDIN')
parser.add_argument('-n', '--name',       default='')
parser.add_argument('-e', '--email',      default='')
parser.add_argument('-s', '--subject',    default='')
parser.add_argument('-f', '--file',       action='append')
parser.add_argument('-S', '--sage',       help='Alias for --email=sage',
    dest='email', action='store_const', const='sage')
parser.add_argument('-p', '--password',   default='')
parser.add_argument('--cookie',     default='/tmp/kc.post.cookies')
parser.add_argument('--user-agent',
    default='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' )
args = parser.parse_args()

if args.text == '-':
    args.text = sys.stdin.read(-1)

if len(args.url) < 5:
    args.url = '%s/%s/' % (base_url, args.url)

session = requests.Session()
session.headers.update({'User-Agent': args.user_agent})
session.cookies.update({'cookieConsent': 'true'})

KCPost  = ChanUpload(base_url, session)
KCPost.loadCookies(args.cookie)

result = KCPost.post(
    args.url,
    text=args.text,
    subject=args.subject,
    email=args.email,
    name=args.name,
    files=args.file
)

print(base_url + result['redirect'])

KCPost.storeCookies(args.cookie)

